[package]
name = "toc-rs"
version = "0.2.7"
edition = "2021"

[dependencies]
glob = "0.3.0"
crossterm = "0.27.0"
getch = "0.3.1"
chrono = "0.4"
reqwest = { version = "0.11", features = ["blocking"] }
