[package]
name = "fntoc"
version = "0.1.7"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glob = "0.3.0"
colored = "2.0"
reqwest = { version = "0.11", features = ["blocking"] }
i_o = { path = "../i_o" }
